### ISSUE TITLE
Bio length can exceed description field max size in database.

### ISSUE THREAD

**Issue by nzdjb** [tveastman/secateur#35]
It appears that some Twitter users are able to exceed the 160 character bio limit. This can break Secateur as the limit on secateur_account.description is 200 (https://github.com/tveastman/secateur/blob/13085e9c0f32055a563a00e2694484919dd15b3f/secateur/migrations/0015_auto_20200610_1043.py#L21).

The account `@saylor` is an example of this, with a bio length of 201 characters.

Interestingly, this doesn't seem to break on secateur.app. Have you increased description's length there?

Log from postgres:
```
secateur-postgres-1  | 2022-06-19 08:57:56.591 UTC [40] ERROR:  value too long for type character varying(200)
secateur-postgres-1  | 2022-06-19 08:57:56.591 UTC [40] STATEMENT:  INSERT INTO "secateur_account" ("user_id", "profile_updated", "screen_name", "name", "description", "location", "profile_image_url_https", "profile_banner_url", "created_at", "favourites_count", "followers_count", "friends_count", "statuses_count", "listed_count") VALUES (244647486, '2022-06-19T08:57:56.590097+00:00'::timestamptz, 'saylor', 'Michael Saylor⚡️', '$MSTR Founder & CEO | @MIT Aerospace | bio @ https://t.co/9Zlq0oHqyh | free education @ https://t.co/4L1s0iwzQ6 | #Bitcoin is https://t.co/ejezpjeUZ4 & https://t.co/SLbKcP1BnV. | All tweets are my own.', 'Miami Beach, FL', 'https://pbs.twimg.com/profile_images/1485632175932383235/8t0DGo6V_normal.jpg', 'https://pbs.twimg.com/profile_banners/244647486/1606261344', '2011-01-29T20:11:04+00:00'::timestamptz, 2720, 2569731, 605, 3456, 14863) ON CONFLICT ("user_id") 
DO UPDATE SET "user_id" = EXCLUDED."user_id", "profile_updated" = EXCLUDED."profile_updated", "screen_name" = EXCLUDED."screen_name", "name" = EXCLUDED."name", "description" = EXCLUDED."description", "location" = EXCLUDED."location", "profile_image_url_https" = EXCLUDED."profile_image_url_https", "profile_banner_url" = EXCLUDED."profile_banner_url", "created_at" = EXCLUDED."created_at", "favourites_count" = EXCLUDED."favourites_count", "followers_count" = EXCLUDED."followers_count", "friends_count" = EXCLUDED."friends_count", "statuses_count" = EXCLUDED."statuses_count", "listed_count" = EXCLUDED."listed_count" RETURNING "user_id"
```

Trace from Secateur:
```
Request Method: POST
Request URL: http://127.0.0.1:5000/block/

Django Version: 4.0.4
Python Version: 3.9.13
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django.contrib.sites',
 'django.contrib.flatpages',
 'django.contrib.postgres',
 'django_celery_beat',
 'social_django',
 'bootstrap4',
 'request',
 'psqlextra',
 'waffle',
 'secateur.apps.SecateurConfig']
Installed Middleware:
['opentelemetry.instrumentation.django.middleware._DjangoMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'xff.middleware.XForwardedForMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'request.middleware.RequestMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
 'csp.middleware.CSPMiddleware',
 'waffle.middleware.WaffleMiddleware',
 'django_structlog.middlewares.RequestMiddleware',
 'django_structlog.middlewares.CeleryMiddleware']



Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/venv/lib/python3.9/site-packages/opentelemetry/instrumentation/psycopg2/__init__.py", line 184, in execute
    return _cursor_tracer.traced_execution(
  File "/venv/lib/python3.9/site-packages/opentelemetry/instrumentation/dbapi/__init__.py", line 411, in traced_execution
    return query_method(*args, **kwargs)

The above exception (value too long for type character varying(200)
) was the direct cause of the following exception:
  File "/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/venv/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/venv/lib/python3.9/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/app/secateur/views.py", line 178, in form_valid
    account = user.get_account_by_screen_name(form.cleaned_data["screen_name"])
  File "/app/secateur/models.py", line 134, in get_account_by_screen_name
    return tasks.get_user(self.pk, screen_name=screen_name)
  File "/venv/lib/python3.9/site-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/venv/lib/python3.9/site-packages/celery/app/task.py", line 392, in __call__
    return self.run(*args, **kwargs)
  File "/app/secateur/tasks.py", line 79, in get_user
    account = models.Account.get_account(twitter_user)
  File "/app/secateur/models.py", line 207, in get_account
    return cls.get_accounts(arg, now=now).get()
  File "/app/secateur/models.py", line 239, in get_accounts
    cls.objects.bulk_upsert(conflict_target=["user_id"], rows=rows)
  File "/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/psqlextra/query.py", line 390, in bulk_upsert
    return self.bulk_insert(rows, return_model, using=using)
  File "/venv/lib/python3.9/site-packages/psqlextra/query.py", line 168, in bulk_insert
    objs = compiler.execute_sql(return_id=not return_model)
  File "/venv/lib/python3.9/site-packages/psqlextra/compiler.py", line 96, in execute_sql
    cursor.execute(sql, params)
  File "/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/venv/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/venv/lib/python3.9/site-packages/opentelemetry/instrumentation/psycopg2/__init__.py", line 184, in execute
    return _cursor_tracer.traced_execution(
  File "/venv/lib/python3.9/site-packages/opentelemetry/instrumentation/dbapi/__init__.py", line 411, in traced_execution
    return query_method(*args, **kwargs)

Exception Type: DataError at /block/
Exception Value: value too long for type character varying(200)
```

**Comment by tveastman** [comment]
Weird! in my production database it was 1000

```
secateur=# \d+ secateur_account;
                                                      Table "public.secateur_account"
         Column          |           Type           | Collation | Nullable | Default | Storage  | Compression | Stats target | Description 
-------------------------+--------------------------+-----------+----------+---------+----------+-------------+--------------+-------------
 user_id                 | bigint                   |           | not null |         | plain    |             |              | 
 screen_name             | character varying(100)   |           |          |         | extended |             |              | 
 profile_updated         | timestamp with time zone |           |          |         | plain    |             |              | 
 name                    | character varying(200)   |           |          |         | extended |             |              | 
 created_at              | timestamp with time zone |           |          |         | plain    |             |              | 
 description             | character varying(1000)  |           |          |         | extended |             |              | 
 favourites_count        | integer                  |           |          |         | plain    |             |              | 
 followers_count         | integer                  |           |          |         | plain    |             |              | 
 friends_count           | integer                  |           |          |         | plain    |             |              | 
 listed_count            | integer                  |           |          |         | plain    |             |              | 
 location                | character varying(1000)  |           |          |         | extended |             |              | 
 profile_banner_url      | character varying(1000)  |           |          |         | extended |             |              | 
 profile_image_url_https | character varying(1000)  |           |          |         | extended |             |              | 
 statuses_count          | integer                  |           |          |         | plain    |             |              | 
Indexes:
```

I have no memory of manually making that change, but perhaps I did and never followed it up with the code. Good spotting!
